FIND_PATH(LMDB_INCLUDE_DIR NAMES lmdb.h)
FIND_LIBRARY(LMDB_LIBRARY NAMES lmdb)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LMDB DEFAULT_MSG LMDB_LIBRARY LMDB_INCLUDE_DIR)

IF(LMDB_FOUND)
    SET(LMDB_LIBRARIES ${LMDB_LIBRARY})
    SET(LMDB_INCLUDE_DIRS ${LMDB_INCLUDE_DIR})
ELSE(LMDB_FOUND)
    SET(LMDB_LIBRARIES)
    SET(LMDB_INCLUDE_DIRS)
ENDIF(LMDB_FOUND)

MARK_AS_ADVANCED(LMDB_INCLUDE_DIRS LMDB_LIBRARIES)